pipeline {
  agent any

  options {
    timestamps()
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Prepare env file') {
      steps {
        dir('Front-End') {
          withCredentials([file(credentialsId: 'frontend-env-file', variable: 'ENV_FILE')]) {
            bat 'copy "%ENV_FILE%" ".env" /Y'
          }
        }
      }
    }

    stage('Install dependencies') {
      steps {
        dir('Front-End') {
          bat 'npm install'
        }
      }
    }

    stage('Lint') {
      steps {
        dir('Front-End') {
          bat 'npm run lint'
        }
      }
    }

    stage('Build') {
      steps {
        dir('Front-End') {
          bat 'npm run build'
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'Front-End/.next/**', onlyIfSuccessful: true, allowEmptyArchive: true
    }
  }
}
